services:
  mysql-database:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: gestion_clientes
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: